### PR TITLE
Redis Driver ignores masters with null params

### PR DESCRIPTION
**Pull request by purinda**
Fix the issue of not merging discovered masters when params is null.

### CODE REVIEW

**Comment by nedimdzendzo** [comment]
:+1:

**Comment by y2khjh** [comment]
We are always using Sentinel right? What the reason we cannot get the params properly set?

**Comment by purinda** [comment]
driver expects sentinel connection parameters which is passed in, and it also find masters (what you want). but that wouldn't get used unless this check is there.

**Comment by y2khjh** [comment]
seems will work :+1:

**Comment by jordonsc** [comment]
Any chance of tests?

**Comment by purinda** [comment]
Yeah, thats why I haven't merged it yet. The way I can think of to test this would be to add sentinel as a requirement to run tests. If you are okay with it?

**Pull request merged**
